services:
  origin:
    image: mendhak/http-https-echo
    ports:
      - "8080:8080"

  wait0:
    build: ..
    depends_on:
      - origin
    ports:
      - "8082:8082"
    volumes:
      - ./wait0.yaml:/wait0.yaml:ro
      - wait0-data:/data

volumes:
  wait0-data:
